# -*- coding: utf-8 -*-
"""BankNote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjQz9-QAX99VSCZPQXxKXjGgebJVeWwK
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

from google.colab import drive
drive.mount('/content/drive')

BankData=pd.read_csv("/content/drive/MyDrive/BankNote_Authentication.csv")

X = BankData.iloc[:, :3]
y = BankData.iloc[:, -1]

regressor = LinearRegression()

regressor.fit(X, y)

pickle.dump(regressor, open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))

print(model.predict([[1, 1, 2]]))